version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: db_container
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db  
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USERNAME}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DATABASE}
  # db_test:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: test
  #     POSTGRES_PASSWORD: test
  #     POSTGRES_DB: test_db
  #   ports:
  #     - "5433:5432"                      
  #   volumes:
  #     - postgres_test_data:/var/lib/postgresql/data
  #     - ./db/:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
  # postgres_test_data: